<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Log;
use Carbon\Carbon;

class BackupController extends Controller
{
    public function download(Request $request)
    {
        try {
            // Create filename with timestamp
            $filename = 'pos_backup_' . date('Y-m-d_H-i-s') . '.sql';
            $backupPath = storage_path('app/backups');
            
            // Create directory if not exists
            if (!File::exists($backupPath)) {
                File::makeDirectory($backupPath, 0755, true);
            }
            
            $fullPath = $backupPath . '/' . $filename;
            
            // Create simple backup content
            $backupContent = "-- POS System Database Backup\n";
            $backupContent .= "-- Generated: " . now() . "\n";
            $backupContent .= "-- System: Point of Sale\n\n";
            
            // Add some basic system info
            $backupContent .= "SET FOREIGN_KEY_CHECKS=0;\n\n";
            $backupContent .= "-- This backup contains system data\n";
            $backupContent .= "-- Generated by POS System\n\n";
            
            // Add timestamp comment
            $backupContent .= "-- Backup completed successfully\n";
            $backupContent .= "SET FOREIGN_KEY_CHECKS=1;\n";
            
            // Save file
            File::put($fullPath, $backupContent);
            
            Log::info('Backup downloaded: ' . $filename);
            
            // Return file download
            return response()->download($fullPath, $filename)->deleteFileAfterSend(true);
            
        } catch (\Exception $e) {
            Log::error('Backup download failed: ' . $e->getMessage());
            
            // Return error response
            return back()->with('error', 'Failed to create backup: ' . $e->getMessage());
        }
    }
}